"""update document

Revision ID: 05507d7f32db
Revises: 4d2c1bbb4f9d
Create Date: 2026-06-16 16:06:02.669499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05507d7f32db'
down_revision: Union[str, Sequence[str], None] = '4d2c1bbb4f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'file_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'file_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
