"""add session_id columns

Revision ID: ddfb6fcc8e2d
Revises: a4f7c1b2d9e0
Create Date: 2026-06-22 15:13:54.734928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddfb6fcc8e2d'
down_revision: Union[str, Sequence[str], None] = 'a4f7c1b2d9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('session_id', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('session_id', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('session_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'session_id')
    op.drop_column('documents', 'session_id')
    op.drop_column('conversations', 'session_id')
    # ### end Alembic commands ###
